backend:
  name: github
  repo: beppek/y-made-homepage

media_folder: static/assets/media
public_folder: assets

collections:
  - name: gallery
    label: Gallery
    label_singular: Image
    folder: content/gallery
    create: true
    fields:
      - { name: file, label: File, widget: image }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
  - name: info
    label: Information
    folder: content/info
    create: false
    fields:
      - { name: title, label: Title }
      - { name: subtitle, label: Subitle }
      - { name: content, label: Content, widget: markdown }
