backend:
  name: github
  repo: beppek/y-made-homepage

media_folder: static/assets
public_folder: assets

collections:
  - name: gallery
    label: Gallery
    label_singular: Image
    folder: gallery
    create: true
    fields:
      - { name: file, label: File, widget: image }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
  - name: info
    label: Information
    folder: 'content/info'
    create: false
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
